# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Servers and Scurvy
subtitle: Hacking all the planets
author: Geoff Davis
email:
description: > # this means to ignore newlines until "baseurl:"
  Servers, programming, networking
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://geoffdavis.github.io"
twitter_username: pottedpork
github_username:  geoffdavis

# Build settings
markdown: rdiscount
